### ISSUE TITLE
Mark Assignment 3 for D Conner

### ISSUE THREAD

**Issue by d-conner** [d-conner/week_03#1]
4b0f634

**Comment by rharrington31** [comment]
1. Great answer. Very complete answer - you highlighted some of the specific issues that this dataset faces with using the default `col_type` parser.
2. Good - I probably would have personally done the `select` before the `mutate`, but that doesn't actually matter.
3. Good. Would have also liked to see histograms for some of the continuous variables, but this would be a good start.
4. Good. You could simplify this to `evMotor_flag = ! is.na(evMotor)` as well.
5. Nice job.
6. Good job. I appreciate you doing this programatically. To improve that even further, instead of hardcoding the `filter(n >2210)` you could have used a rank function and selected the top 5. Also, nice job using the vector as part of your filter statement.
7. Great! I appreciate you building off of some of the previous questions from the homework. Great interpretations. I'd be interested to see the count of electric vehicles vs traditional over time as well for your 2nd question.
8. I'm really interested to see this project come to life. Interesting dataset(s). Great question. Well thought out approach!

General comment - I really appreciate your use of comments throughout your code. It's great practice to keep up!
